### ISSUE TITLE
Support X2D

### ISSUE THREAD

**Issue by samsam-rolon** [jyvern/rfp2mqtt#2]
Bonjour,
Un guide existe-il pour le support du X2D ?
Merci

**Comment by jyvern** [comment]
Bonjour, 
Je ne connais pas ce genre d'équipement n'en ayant pas. Ce que je peux vous dire c'est qu'il n'y a pas de guide spécifique pour chaque protocole supporté par le RFP1000. Pour chacun d'eux, un topic MQTT est construit sous la forme, exemple X2D Shutter, x2d-shutter/11-<code construit par rfp1000> et la message est une chaine JSON composée des infos reçues dans le message du RFP1000.

**Comment by samsam-rolon** [comment]
Dans mon cas, c'est le pilotage X2D de radiateurs électrique.
Il manque un peu de documentation en toute franchise quand on débute sur le mqtt et qu'on essaye de comprendre le fonctionnement du script pour envoyer vers le broker mqtt.
Typiquement, j'ai du mal a comprendre comment envoyer mes commandes "ON" / "OFF" ...
Elles ressemblent à ça nativement dans Jeedom :
![image](https://user-images.githubusercontent.com/25209236/104428310-9cd23d00-5584-11eb-8dcb-73ad61c3ea20.png)
![image](https://user-images.githubusercontent.com/25209236/104428277-93e16b80-5584-11eb-9e75-a35d9f02eab3.png)

Voila ma section périphérique :)
```yml
actuators:
    -
        id: a1
        name: Chauffage_Bureau
        protocol: x2dhaelec
        topic: home/action/heater
        command: ON/OFF/ASSOC

```
